# Generated by Django 4.2.5 on 2024-01-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_month', models.IntegerField()),
                ('name_month', models.CharField(max_length=255)),
                ('count_day', models.IntegerField()),
            ],
        ),
    ]
