# Generated by Django 4.2.5 on 2024-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='url_name',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='month',
            name='name_month',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='number_month',
            field=models.IntegerField(unique=True),
        ),
    ]
