# Generated by Django 4.2.5 on 2024-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_month_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_day', models.IntegerField(unique=True)),
                ('url_name', models.SlugField(unique=True)),
            ],
        ),
    ]
