# Generated by Django 4.2.5 on 2024-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='date_holiday',
            field=models.CharField(default='', max_length=255),
        ),
    ]
