# Generated by Django 4.2.5 on 2024-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_holiday_date_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date_holiday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_month',
            field=models.IntegerField(default=1),
        ),
    ]
