# Generated by Django 4.2.5 on 2024-02-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_remove_holiday_date_holiday_holiday_date_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
