# Generated by Django 4.2.5 on 2024-02-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_day_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
