# Generated by Django 4.2.5 on 2024-02-08 20:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_holiday_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='holiday',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date_day',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date_month',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_published',
        ),
    ]
