# Generated by Django 4.2.5 on 2024-02-08 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_alter_holiday_managers_remove_holiday_date_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='date_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.day'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='month_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_page.month'),
        ),
    ]
