# Generated by Django 4.2.5 on 2024-02-08 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_holiday_date_id_holiday_month_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date_id',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='month_id',
            new_name='month',
        ),
    ]
