# Generated by Django 4.2.5 on 2024-02-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_alter_holiday_day_alter_holiday_month'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='holiday',
            managers=[
            ],
        ),
    ]
