# Generated by Django 4.2.5 on 2024-02-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_alter_holiday_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='url_name',
            new_name='slug',
        ),
    ]
