# Generated by Django 4.2.5 on 2024-02-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_rename_url_name_month_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='url_name',
            new_name='slug',
        ),
    ]
