# Generated by Django 4.2.5 on 2024-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_rename_url_name_day_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='url_name',
            new_name='slug',
        ),
    ]
