# Generated by Django 4.2.5 on 2024-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_rename_url_name_holiday_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='day',
        ),
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.ManyToManyField(blank=True, to='main_page.day'),
        ),
    ]
