# Generated by Django 4.2.5 on 2024-02-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_remove_holiday_day_holiday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='day',
            field=models.ManyToManyField(blank=True, to='main_page.day'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='day',
        ),
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_page.day'),
            preserve_default=False,
        ),
    ]
