# Generated by Django 4.2.5 on 2024-02-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_month_day_remove_holiday_day_holiday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='day',
        ),
    ]
