# Generated by Django 4.2.5 on 2024-02-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_remove_month_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='day',
            field=models.ManyToManyField(blank=True, to='main_page.day'),
        ),
    ]
