# Generated by Django 4.2.5 on 2024-02-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_alter_month_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='days', to='main_page.day'),
        ),
    ]
