# Generated by Django 4.2.5 on 2024-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_alter_month_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ManyToManyField(blank=True, related_name='month', to='main_page.month'),
        ),
    ]
