# Generated by Django 4.2.5 on 2024-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_remove_holiday_day_remove_holiday_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.ManyToManyField(blank=True, to='main_page.day'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='month',
            field=models.ManyToManyField(blank=True, to='main_page.month'),
        ),
    ]
