# Generated by Django 4.2.5 on 2024-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0027_holiday_day_holiday_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name_plural': 'Праздники'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name_plural': 'Месяцы'},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='international',
            field=models.BooleanField(default=False, verbose_name='Статус международного'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='ordinary_holiday',
            field=models.BooleanField(default=False, verbose_name='Статус обычного'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='worldwide',
            field=models.BooleanField(default=False, verbose_name='Статус всемирного'),
        ),
    ]
