# Generated by Django 4.2.5 on 2024-03-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0029_holiday_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description_holi',
            field=models.TextField(blank=True),
        ),
    ]
