# Generated by Django 4.2.5 on 2024-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0030_holiday_description_holi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.ManyToManyField(blank=True, related_name='months', to='main_page.month'),
        ),
    ]
