# Generated by Django 4.2.5 on 2024-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0032_fileuploadholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadholiday',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='image', verbose_name='Файл'),
        ),
    ]
