# Generated by Django 4.2.5 on 2024-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0033_alter_fileuploadholiday_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUploadHoliday',
        ),
    ]
