# Generated by Django 4.2.5 on 2024-04-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0034_uploadfilemodel_delete_fileuploadholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фото'),
        ),
    ]
