# Generated by Django 4.2.5 on 2024-04-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0035_holiday_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileModel',
            new_name='AddFileForm',
        ),
    ]
