# Generated by Django 4.2.5 on 2024-04-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0036_rename_uploadfilemodel_addfileform'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='file',
            field=models.FileField(blank=True, upload_to='image'),
        ),
    ]
