<<<<<<< HEAD
# Generated by Django 4.2.5 on 2024-01-26 17:09
=======
# Generated by Django 4.2.5 on 2024-01-25 18:39
>>>>>>> 34c923ab9f1d774ab4538e3c993e2eb01c75c4c5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['-time_create'], name='women_women_time_cr_9f33c2_idx'),
        ),
    ]
