# Generated by Django 4.2.5 on 2024-02-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_tagpost_alter_women_cat_women_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='tags',
            new_name='tagies',
        ),
    ]
