# Generated by Django 4.2.5 on 2024-02-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_women_husb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='husb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='women', to='women.husband'),
        ),
    ]
