# Generated by Django 4.2.5 on 2024-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0010_alter_women_husb'),
    ]

    operations = [
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
