# Generated by Django 4.2.5 on 2024-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.DateField(),
        ),
    ]
