# Generated by Django 4.2.5 on 2024-01-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.IntegerField()),
                ('telegram_id', models.IntegerField(blank=True)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OneNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_holiday', models.DateTimeField()),
                ('name_holiday', models.CharField(max_length=100)),
                ('desc_holiday', models.TextField(max_length=600)),
                ('fill_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
