# Generated by Django 4.2.5 on 2024-01-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_feedback_onenotifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
