# Generated by Django 4.2.5 on 2024-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_users', models.IntegerField()),
                ('telegram_id', models.IntegerField(blank=True)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
