# Generated by Django 4.2.5 on 2024-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='telegram_id',
            field=models.IntegerField(default=None),
        ),
    ]
