# Generated by Django 4.2.5 on 2024-01-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_feedback_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='telegram_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
