# Generated by Django 4.2.5 on 2024-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_feedback_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
